SELECT
  customer_name,
  CASE
    WHEN SUM(CASE WHEN status = 'DELIVERED' THEN 1 ELSE 0 END) = COUNT(*) THEN 'COMPLETED'
    WHEN SUM(CASE WHEN status = 'DELIVERED' THEN 1 ELSE 0 END) > 0 AND SUM(CASE WHEN status IN ('CREATED', 'SUBMITTED') THEN 1 ELSE 0 END) > 0 THEN 'IN PROGRESS'
    WHEN SUM(CASE WHEN status = 'SUBMITTED' THEN 1 ELSE 0 END) > 0 AND SUM(CASE WHEN status <> 'DELIVERED' THEN 1 ELSE 0 END) = COUNT(*) THEN 'AWAITING PROGRESS'
    ELSE 'AWAITING SUBMISSION'
  END AS final_status
FROM customer_order
group by customer_name;
